stm_bm(["menu74f9",430,"./menus/","blank.gif",2,"","",1,0,0,0,0,1,0,0,"","",0],this);
stm_bp("p0",[0,4,0,0,0,2,16,0,100,"",-2,"",-2,90,0,0,"#000000","transparent","",3,0,0,"#ffffff"]);
stm_ai("p0i0",[0,"Proceso Fin de Mes ","","",-1,-1,0,"","_self","","","bullet1.gif","bullet2.gif",16,16,0,"","",0,0,0,0,1,"#73a8b7",0,"#b3ccd3",0,"","",3,3,0,0,"#ffffff","#ffffff","#ffffff","#000000","bold 12pt Arial","bold 12pt Arial",0,0]);
stm_bp("p1",[1,4,0,0,0,3,16,0,100,"",-2,"",-2,60,0,0,"#000000","#ffffff","",3,1,1,"#73a8b7"]);
stm_aix("p1i0","p0i0",[0,"Diferencias Inventarios","","",-1,-1,0,"./bal_act_inv_v3.php","mainFrame","","","insert2.gif","insert2.gif",16,16,0,"","",0,0,0,0,1,"#ebf8ff",0,"#acd2dd",0,"","",3,3,0,0,"#ffffff","#ffffff","#333333","#333333","12pt Arial","12pt Arial"]);
stm_aix("p1i1","p1i0",[0,"Modificación de Diferencias","","",-1,-1,0,"./bal_dif_mod.php"]);
stm_aix("p1i2","p1i0",[0,"Inventario de Fin de Mes","","",-1,-1,0,"./pan_invfm_cap.php","mainFrame","","","edit.gif","edit.gif"]);
stm_aix("p1i3","p1i0",[0,"Listado de Inventario de Panaderías","","",-1,-1,0,"./bal_ifm_lis.php","_self","","","search.gif","search.gif"]);
stm_aix("p1i4","p1i3",[0,"Listado de Diferencias de Inventario","","",-1,-1,0,"ListadoDiferenciasInventario.php","mainFrame"]);
stm_aix("p1i5","p1i0",[0,"Actualizar Consumos Mensuales","","",-1,-1,0,"./bal_act_con.php"]);
stm_aix("p1i6","p1i4",[0,"Auxiliar de Inventario","","",-1,-1,0,"AuxiliarInventario.php"]);
stm_aix("p1i7","p1i4",[0,"Arrastre de inventario por periodo","","",-1,-1,0,"InventarioArrastrePeriodo.php"]);
stm_aix("p1i8","p1i0",[0,"Traspaso de Avio","","",-1,-1,0,"./pan_avi_tra.php","_self","","","insert.gif","insert.gif"]);
stm_aix("p1i9","p1i0",[0,"Porcentajes de Distribución de Gas","","",-1,-1,0,"DistribucionGas.php"]);
stm_aix("p1i10","p1i0",[0,"Porcentajes de Distribución de Gastos","","",-1,-1,0,"GastosPorcentajesDistribucion.php"]);
stm_aix("p1i11","p1i0",[0,"Impresión de Hojas de Inventario","","",-1,-1,0,"./bal_ifm_con_v2.php"]);
stm_aix("p1i12","p1i0",[0,"Enviar inventarios de FIN de mes<BR>a las panaderias","","",-1,-1,0,"bal_ifm_pan.php"]);
stm_aix("p1i13","p1i0",[0,"Enviar inventarios de INICIO de mes<BR>a las panaderias","","",-1,-1,0,"pan_act_inv_pan.php"]);
stm_aix("p1i14","p1i0",[0,"Archivo de Inventarios de fin de mes","","",-1,-1,0,"./bal_ifm_mail.php","_self"]);
stm_aix("p1i15","p1i4",[0,"Listado de Avío Controlado","","",-1,-1,0,"./bal_avio_con.php"]);
stm_aix("p1i16","p1i4",[0,"Control de Encargados","","",-1,-1,0,"./bal_enc_cap.php"]);
stm_aix("p1i17","p1i4",[0,"Consulta de Gastos","","",-1,-1,0,"./ros_gas_con_v2.php"]);
stm_ep();
stm_ai("p0i1",[6,1,"#cccccc","",0,0,0]);
stm_aix("p0i2","p0i0",[0,"Estado de Resultados  "]);
stm_bpx("p2","p1",[]);
stm_aix("p2i0","p1i0",[0,"Imprimir Balances Panaderias","","",-1,-1,0,"ImprimirBalancesPanaderias.php"]);
stm_aix("p2i1","p1i0",[0,"Imprimir Balances Rosticerias","","",-1,-1,0,"ImprimirBalancesRosticerias.php"]);
stm_aix("p2i2","p1i0",[0,"Imprimir Balances Inmobiliarias","","",-1,-1,0,"ImprimirBalancesInmobiliarias.php"]);
stm_aix("p2i3","p1i4",[0,"Histórico de Balances","","",-1,-1,0,"./bal_his_bal.php"]);
stm_aix("p2i4","p1i4",[0,"Comparativo entre Panaderías","","",-1,-1,0,"ComparativoBalancesPanaderias.php"]);
stm_aix("p2i5","p1i4",[0,"Comparativo de conceptos de balance","","",-1,-1,0,"BalancesComparativoDatosAnual.php"]);
stm_aix("p2i6","p1i4",[0,"Comparativo de Datos de Balance contra Gastos","","",-1,-1,0,"./bal_com_bal_gas.php"]);
stm_aix("p2i7","p1i3",[0,"Resultado de reporte Anual","","",-1,-1,0,"ResultadoReporteAnual.php"]);
stm_aix("p2i8","p1i4",[0,"Reporte de utilidades netas","","",-1,-1,0,"ReporteUtilidadesNetas.php"]);
stm_aix("p2i9","p1i4",[0,"Comparativo de efectivos contra I.V.A.","","",-1,-1,0,"ComparativoEfectivosIVA.php"]);
stm_aix("p2i10","p1i4",[0,"Comparativo de efectivos contra gastos varios","","",-1,-1,0,"ComparativoEfectivosGastosVarios.php"]);
stm_ep();
stm_aix("p0i3","p0i1",[]);
stm_aix("p0i4","p0i0",[0,"Gastos Especiales  "]);
stm_bpx("p3","p1",[]);
stm_aix("p3i0","p1i0",[0,"Catalogo de Gastos de Oficina","","",-1,-1,0,"./catalogo_gastos_caja.php","mainFrame","Catálogo de Gastos de Caja"]);
stm_aix("p3i1","p1i4",[0,"Consultas","","",-1,-1,0,"./bal_gca_con.php"]);
stm_aix("p3i2","p0i1",[]);
stm_aix("p3i3","p1i0",[0,"Gastos de Oficina","","",-1,-1,0,"./bal_gas_caj.php","mainFrame","Gastos de Caja"]);
stm_aix("p3i4","p1i0",[0,"Gastos de Oficina (Pollos)","","",-1,-1,0,"./bal_gas_ros.php"]);
stm_aix("p3i5","p1i3",[0,"Consulta","","",-1,-1,0,"./bal_gof_con_v2.php","mainFrame","Consulta"]);
stm_aix("p3i6","p1i2",[0,"Modificación de gastos<BR>de oficina","","",-1,-1,0,"./bal_gast_caja_mod.php","mainFrame","Consulta"]);
stm_aix("p3i7","p1i0",[0,"Dispersión de Gastos de Oficina","","",-1,-1,0,"DispersionGastosCaja.php"]);
stm_aix("p3i8","p1i14",[0,"Cargar Archivo de Gastos","","",-1,-1,0,"./bal_gas_caj_arc.php"]);
stm_aix("p3i9","p0i1",[]);
stm_aix("p3i10","p1i0",[0,"Gastos pagados por otras compañías","","",-1,-1,0,"./bal_goc_cap.php"]);
stm_aix("p3i11","p3i5",[0,"Consultas","","",-1,-1,0,"./bal_goc_con.php"]);
stm_aix("p3i12","p0i1",[]);
stm_aix("p3i13","p1i4",[0,"Captura de Gastos Fijos","","",-1,-1,0,"./bal_gas_caj_fij.php"]);
stm_aix("p3i14","p1i4",[0,"Consulta de Gastos Fijos","","",-1,-1,0,"./bal_gas_caj_fij_mod.php"]);
stm_aix("p3i15","p1i4",[0,"Listado de Gastos Fijos","","",-1,-1,0,"./bal_gas_caj_fij_lis.php"]);
stm_aix("p3i16","p1i4",[0,"Aplicar Gastos Fijos","","",-1,-1,0,"./bal_gas_caj_fij_gen.php"]);
stm_aix("p3i17","p0i1",[]);
stm_aix("p3i18","p1i4",[0,"Pagos Hechos Anticipadamente","","",-1,-1,0,"PagosAnticipados.php"]);
stm_aix("p3i19","p0i1",[]);
stm_aix("p3i20","p1i14",[0,"Reserva de gastos para balance","","",-1,-1,0,"ReservaGastos.php"]);
stm_ep();
stm_aix("p0i5","p0i1",[]);
stm_aix("p0i6","p0i0",[0,"Reservas  "]);
stm_bpx("p4","p1",[]);
stm_aix("p4i0","p1i0",[0,"Catalogo de reservas","","",-1,-1,0,"ReservasCatalogo.php","mainFrame","Catálogo de Reservas"]);
stm_aix("p4i1","p0i1",[]);
stm_aix("p4i2","p1i0",[0,"Control de reservas","","",-1,-1,0,"ReservasControl.php"]);
stm_aix("p4i3","p1i4",[0,"Consultas","","",-1,-1,0,"./bal_res_con.php"]);
stm_aix("p4i4","p1i4",[0,"Reservas no corregidas","","",-1,-1,0,"./bal_res_nco.php"]);
stm_ep();
stm_aix("p0i7","p0i1",[]);
stm_aix("p0i8","p0i0",[0,"Listados  ","","",-1,-1,0,"Reporte"]);
stm_bpx("p5","p1",[]);
stm_aix("p5i0","p1i0",[0,"Saldo de Proveedores","","",-1,-1,0,"./bal_sal_pro.php","mainFrame","","","search.gif","search.gif",-1,-1]);
stm_aix("p5i1","p5i0",[0,"Existencias en Materia Prima","","",-1,-1,0,"./bal_exc_fis.php"]);
stm_aix("p5i2","p5i0",[0,"Ventas Globales","","",-1,-1,0,"./bal_ven_con.php"]);
stm_aix("p5i3","p5i0",[0,"Estimación Anual","","",-1,-1,0,"./bal_com_nombal.php"]);
stm_aix("p5i4","p5i0",[0,"Listado de Carpiterías","","",-1,-1,0,"./bal_lis_mad.php"]);
stm_aix("p5i5","p5i0",[0,"Listado de Gas / Producción Anual","","",-1,-1,0,"ReporteGasProduccionAnualizado.php"]);
stm_aix("p5i6","p5i0",[0,"Reporte de gastos anualizados","","",-1,-1,0,"ReporteGastosAnualesV2.php"]);
stm_aix("p5i7","p5i0",[0,"Reporte de gastos totalizados anuales","","",-1,-1,0,"ReporteSumaGastosAnualizado.php"]);
stm_aix("p5i8","p5i0",[0,"Reporte de efectivos anuales","","",-1,-1,0,"ReporteEfectivosAnuales.php"]);
stm_aix("p5i9","p1i0",[0,"Reporte de facturas de venta anuales","","",-1,-1,0,"ReporteFacturasVentaAnuales.php","_self","","","","",0,0]);
stm_aix("p5i10","p5i0",[0,"Listado de Cheques de Gastos No Incluidos","","",-1,-1,0,"./ban_gni_con.php"]);
stm_aix("p5i11","p1i4",[0,"Reporte Consolidado","","",-1,-1,0,"./bal_rep_con.php"]);
stm_aix("p5i12","p1i4",[0,"Estimación de alza de precios de producciòn","","",-1,-1,0,"EstimacionAlzaPreciosProduccion.php"]);
stm_aix("p5i13","p1i4",[0,"Costo de Reparto","","",-1,-1,0,"./bal_com_rep.php"]);
stm_aix("p5i14","p1i4",[0,"Listado de Producción Anualizado","","",-1,-1,0,"./bal_com_pro.php"]);
stm_aix("p5i15","p1i4",[0,"Listado de Expendios Anualizados","","",-1,-1,0,"./bal_exp_anu.php"]);
stm_aix("p5i16","p1i4",[0,"Surtido de Gas Mensual","","",-1,-1,0,"./bal_gas_ent_men.php"]);
stm_aix("p5i17","p1i4",[0,"Surtido de productos mensual","","",-1,-1,0,"ReporteProductosMensual.php"]);
stm_aix("p5i18","p1i3",[0,"Comparativo de Clientes Anual","","",-1,-1,0,"./pan_cli_anu.php"]);
stm_aix("p5i19","p1i4",[0,"Comparativo Mensual de Gastos","","",-1,-1,0,"./bal_com_gas_mes.php"]);
stm_aix("p5i20","p1i4",[0,"Estimación por Aumento de Precio","","",-1,-1,0,"./bal_var_har.php"]);
stm_aix("p5i21","p1i4",[0,"Comparativo de piezas producidas","","",-1,-1,0,"ComparativoPiezasProducidas.php"]);
stm_aix("p5i22","p1i4",[0,"Comparativo de costo de inventario por mes","","",-1,-1,0,"InventarioComparativoCostoMensual.php"]);
stm_aix("p5i23","p1i4",[0,"Listado de Gastos de Balance","","",-1,-1,0,"ListadoGastosBalance.php"]);
stm_aix("p5i24","p5i0",[0,"Reporte de pagos de luz","","",-1,-1,0,"PagosLuz.php"]);
stm_aix("p5i25","p5i0",[0,"Facturas de proveedores pendientes de pago al corte","","",-1,-1,0,"FacturasPendientesPagoCorte.php"]);
stm_aix("p5i26","p5i0",[0,"Gastos de talleres","","",-1,-1,0,"GastosTalleres.php"]);
stm_aix("p5i27","p1i4",[0,"Reporte de efectivos con respecto a producción","","",-1,-1,0,"ProduccionTurnosEfectivoReporte.php"]);
stm_aix("p5i28","p1i4",[0,"Reporte de I.E.P.S.","","",-1,-1,0,"IEPSReporte.php"]);
stm_aix("p5i29","p1i4",[0,"Reporte de devoluciones de I.V.A. anualizado","","",-1,-1,0,"ReporteIVADevueltoAnualizado.php"]);
stm_aix("p5i30","p1i4",[0,"Reporte de variación de rezagos anualizado","","",-1,-1,0,"ReporteVariacionRezagoAnualizado.php"]);
stm_aix("p5i31","p1i4",[0,"Comparativo de saldos","","",-1,-1,0,"ComparativoSaldos.php"]);
stm_aix("p5i32","p1i4",[0,"Reporte de compras de proveedores anualizado","","",-1,-1,0,"ReporteComprasProveedoresAnualizado.php"]);
stm_aix("p5i33","p1i4",[0,"Reporte de inventario anualizado","","",-1,-1,0,"ReporteInventarioAnualizado.php"]);
stm_aix("p5i34","p1i4",[0,"Comparativo de ventas anuales","","",-1,-1,0,"ComparativoVentasAnuales.php"]);
stm_aix("p5i35","p1i4",[0,"Reporte de ventas y gastos de rosticerías","","",-1,-1,0,"ReporteVentasGastosRosticerias.php"]);
stm_ep();
stm_aix("p0i9","p0i1",[]);
stm_aix("p0i10","p0i0",[0,"Impuestos  <BR>e IMSS"]);
stm_bpx("p6","p1",[]);
stm_aix("p6i0","p1i0",[0,"Filiales para desglose de impuestos","","",-1,-1,0,"ImpuestosFiliales.php"]);
stm_aix("p6i1","p0i1",[]);
stm_aix("p6i2","p1i0",[0,"Captura de Distribución de Impuestos","","",-1,-1,0,"./ban_imp_cap.php"]);
stm_aix("p6i3","p0i1",[]);
stm_aix("p6i4","p1i14",[0,"Consulta","","",-1,-1,0,"./ban_imp_con.php"]);
stm_aix("p6i5","p0i1",[]);
stm_aix("p6i6","p0i0",[0,"IMSS","","",-1,-1,0,"","_self","","","bullet1.gif","bullet1.gif",16,16,0,"","",0,0,0,0,1,"#73a8b7",0,"#73a8b7",0,"","",3,3,0,0,"#ffffff","#ffffff","#ffffff","#ffffff"]);
stm_aix("p6i7","p0i1",[]);
stm_aix("p6i8","p1i0",[0,"Filiales para desglose de pagos del IMSS","","",-1,-1,0,"IMSSFiliales.php"]);
stm_aix("p6i9","p0i1",[]);
stm_aix("p6i10","p1i14",[0,"Importes Pagados al IMSS","","",-1,-1,0,"./ban_imss_pagos_cap.php"]);
stm_aix("p6i11","p0i1",[]);
stm_aix("p6i12","p5i9",[0,"Desglose de Impuestos","","",-1,-1,0,"./ban_imp_des.php","mainFrame"]);
stm_ep();
stm_ep();
stm_em();
