<table width="95%" >
  <tr>
    <td width="10%">&nbsp;</td>
    <td align="justify">
	  <p align="center"><font size="+1"> C O N T R A T O </font></p>
      <p>CONTRATO DE ARRENDAMIENTO PARA LOCAL COMERCIAL QUE CELEBRAN POR UNA PARTE <strong>{arrendatario}</strong> QUIEN EN LO SUCESIVO SERA DENOMINADO EL ARRENDATARIO Y POR LA OTRA PARTE <strong>{arrendador}</strong> REPRESENTADO POR <strong>{representante_arrendador} </strong>QUIEN EN LO SUCESIVO SERA DENOMINADO EL ARRENDADOR, Y COMO FIADOR DEL ARRENDATARIO <strong>{aval}</strong> AL TENOR DE LAS SIGUIENTES CLAUSULAS: </p>
      <p align="center">D E C L A R A C I O N E S </p>
      <p>PRIMERA.- DECLARA EL ARRENDADOR SER PROPIETARIO DEL INMUEBLE UBICADO EN <br>
      <strong>{direccion_arrendador} </strong></p>
      <p>Y QUE DICHO INMUEBLE CUENTA CON TODOS Y CADA UNO DE LOS SERVICIOS QUE SE REQUIEREN PARA EL USO COMERCIAL DE: <br><strong>{giro} </strong></p>
      <p>SEGUNDA.- DECLARA EL ARRENDADOR QUE ES SU VOLUNTAD DAR EN ARRENDAMIENTO EL INMUEBLE DESCRITO EN EL ANTECEDENTE ANTERIOR. </p>
      <p>TERCERA.- DECLARA EL ARRENDATARIO SER MEXICANO, MAYOR DE EDAD Y CONTAR CON CAPACIDAD JURIDICA PARA CELEBRAR EL PRESENTE CONTRATO. </p>
      <p>CUARTA.- DECLARA EL ARRENDATARIO QUE ES SU VOLUNTAD RENTAR EL LOCAL COMERCIAL A QUE SE REFIERE EL ANTECEDENTE SEGUNDO DEL PRESENTE CONTRATO. </p>
      <p>QUINTA.- DECLARA <strong>{aval}</strong> CON ESTA DE ACUERDO EN ASUMIR EN FORMA MANCOMUNADA Y SOLIDARIA CON EL CAR&Aacute;CTER DE FIADOR LAS OBLIGACIONES QUE SE GENEREN A CARGO DEL ARRENDATARIO DE NOMBRE: <strong>{arrendatario}</strong> EN EL PRESENTE CONTRATO. </p>
      <p>SEXTA.- DECLARAN AMBAS PARTES QUE SU VOLUNTAD NO HA SIDO SORPRENDIDA POR DOLO, ERROR, VIOLENCIA O LESION, ES DECIR, QUE SE ENCUENTRA LIBRE DE VICIOS. </p>
      <p align="center">C L A U S U L A S </p>
      <p>PRIMERA.- EL ARRENDADOR DA EN ARRENDAMIENTO AL ARRENDATARIO EL LOCAL DESCRITO EN EL ANTECEDENTE SEGUNDO DEL PRESENTE CONTRATO, Y ESTE LO RECIBE DE CONFORMIDAD Y A SU ENTERA SATISFACCION. </p>
      <p>SEGUNDA.- EL PERIODO DE ESTE CONTRATO SERA FORZOSO PARA AMBAS PARTES, INICIANDO SU VIGENCIA A PARTIR DEL DIA <strong>{fecha_inicial}</strong> Y VENCIENDO EL DIA <strong>{fecha_final}</strong>. </p>
      <p>TERCERA.- EL ARRENDATARIO PAGARA AL ARRENDADOR POR CONCEPTO DE RENTA MENSUAL LA CANTIDAD DE $ <strong>{cantidad_numero}</strong> *<strong>{cantidad_letra}</strong>* MAS IVA. </p>
      <p>LA RENTA SE CUBRIRA POR MENSUALIDADES ADELANTADAS, DENTRO DE LOS CINCO PRIMEROS DIAS DE CADA MES, EN EL DOMICILIO DEL ARRENDADOR, EL CUAL SE ENCUENTRA UBICADO EN <strong>{direccion_oficina}</strong>. </p>
      <p>CUARTA.- TODAS LAS MENSUALIDADES SERAN PAGADAS COMPLETAS O INTEGRAS, AUN Y CUANDO EL ARRENDATARIO HAYA UTILIZADO EL INMUEBLE MATERIA DEL PRESENTE CONTRATO SOLO UN DIA DEL MES. </p>
    <p>QUINTA.- SI POR CUALQUIER CIRCUNSTANCIA EL ARRENDADOR RECIBE EL PAGO DE LA RENTA EN FECHA DISTINTA A LA ACORDADA, NO SE ENTENDERA MODIFICADO EL PRESENTE CONTRATO EN PERJUICIO DEL ARRENDADOR, EXISTIENDO SIEMPRE LA OBLIGACION PARA EL ARRENDATARIO DE PAGAR EL IMPORTE DE LA RENTA DENTRO DE LOS CINCO PRIMEROS DIAS DE CADA MES, CUBRIENDO UNA PENA CONVENCIONAL DEL 10% MENSUAL. </p>
	</td>
  </tr>
</table>
<br style="page-break-after:always ">
<table width="95%" >
  <tr>
    <td width="10%">&nbsp;</td>
    <td align="justify">
	  <p>SEXTA.- EL ARRENDATARIO NO PODRA BAJO NINGUNA CIRCUNSTANCIA SUBARRENDAR, CEDER, O TRASPASAR TOTAL O PARCIALMENTE LA LOCALIDAD ARRENDADA, SIN EL CONSENTIMIENTO DEL ARRENDADOR, EN CASO DE QUE EL ARRENDADOR ACEPTE QUE EL INMUEBLE MATERIA DEL PRESENTE CONTRATO SEA SUBARRENDADO, SU CONSENTIMIENTO SE TENDRA QUE OTORGAR POR ESCRITO, SOMETIENDOSE, TANTO EL ARRENDATARIO COMO EL SUBARRENDADOR A LO ESTABLECIDO EN LOS ARTICULOS 2480 Y 2481 DEL CODIGO CIVIL PARA EL DISTRITO FEDERAL. </p>
      <p>SEPTIMA.- EL LOCAL COMNERCIAL ARRENDADO SE DESTINARA UNICA Y EXCLUSIVAMENTE PARA <strong>{giro}</strong>, SI EL ARRENDATARIO UTILIZA EL LOCAL COMERCIAL ARRENDADO PARA CUALQUIER OTRA ACTIVIDAD DISTINTA A LA AQU&Iacute; ESTIPULADA SIN CONSENTIMIENTO PREVIO DEL ARRENDADOR. SERA MOTIVO SUFICIENTE PARA RESCINDIR EL CONTRATO Y EL ARRENDATARIO ESTARA OBLIGADO A DESOCUPARLO AUN Y CUANDO NO HAYA CONCLUIDO EL PERIODO FIJADO EN LA CLAUSULA SEGUNDA DEL PRESENTE CONTRATO. </p>
      <p>OCTAVA.- EL ARRENDATARIO MANIFIESTA QUE RECIBE LA LOCALIDAD ARRENDADA EN BUEN ESTADO PARA SERVIR AL USO CONVENIDO Y CON TODOS SUS SEVICIOS, DANDOSE POR RECIBIDO A SU ENTERA SATISFACCION DE LA MISMA , ASIMISMO, EL ARRENDATARIO QUEDA OBLIGADO A HACER LAS REPARACIONES DE AQUELLOS DETERIOROS QUE SUFRA EL LOCAL ARRENDADO Y PAGAR EL IMPORTE DE LO FALTANTE O DETERIORADO EN EL INMUEBLE AL PRECIO DE MENUDEO EN ESTA CAPITAL, DE ACUERDO CON LO ESTIPULADO EN EL ARTICULO 2444 DEL CODIGO CIVIL PARA EL DISTRITO FEDERAL, EL ARRENDATARIO CONVIENE Y ESTA DE ACUERDO EN INDEMNIZAR AL ARRENDADOR POR CUALQUIER DETERIORO QUE SUFRA EL INMUEBLE MATERIA DEL PRESENTE CONTRATO POR LAS INSTALACIONES QUE REALICE EL ARRENDATARIO PARA ADECUAR EL LOCAL COMERCIAL PARA: {giro}, DICHAS MODIFICACIONES DEBERAN SER AUTORIZADAS CON ANTERIORIDAD POR EL ARRENDADOR, DEBIENDOSE OTORGAR DICHA AUTORIZACION POR ESCRITO, TODA MEJORA REALIZADA POR EL ARRENDATARIO EN BENEFICIO DEL INMUEBLE MATERIA DEL PRESENTE CONTRATO, NO GENERA OBLIGACION DE NINGUNA ESPECIE A CARGO DEL ARRENDADOR Y SE ENTENDERA QUE QUEDA EN BENEFICIO DEL ARRENDADOR, DE ACUERDO CON LO ESTIPULADO EN EL ARTICULO PRECITADO, QUIEN PODRA EXIGIR EN TODO MOMENTO QUE EL ARRENDATARIO HAGA ENTREGA DEL INMUEBLE TAL Y COMO LO RECIBIO, CUALQUIER ALTERACION SUBSTANCIAL NO AUTORIZADA QUE SE HAGA SOBRE EL INMUEBLE MATERIA DEL PRESENTE CONTRATO, GENERARA UNA OBLIGACION A CARGO DEL ARRENDATARIO Y EN FAVOR DEL ARRENDADOR POR LA CANTIDAD DE $<strong>{cantidad_numero1}</strong> *<strong>{cantidad_letra1}</strong>* MAS IVA. </p>
      <p>NOVENA.- EL ARRENDATARIO CONVIENE Y SE OBLIGA EXPRESAMENTE A: </p>
      <p>&#149;&nbsp; PERMITIR AL ARRENDADOR O A LA PERSONA AUTORIZADA PARA ELLO A INSPECCIONAR LA LOCALIDAD ARRENDADA, SIN MAS LIMITACIONES DE QUE LA INSPECCION SE REALICE EN DIAS Y HORAS HABILES. </p>
      <p>&#149;&nbsp; A INFORMAR AL ARRENDADOR DE CUALQUIER SUSTANCIA QUE PUEDA CONSIDERARSE PELIGROSA (CORROSIVAS, INFLAMABLES, ET.) Y A OBTENER LA AUTORIZACION POR ESCRITO DEL ARRENDADOR PARA SU USO. DESDE ESTE MOMENTO EL ARRENDATARIO ASUME TODA RESPONSABILIDAD CONTRA TERCEROS POR CUALQUIER MAQUINARIA O DEPOSITO DE SUSTANCIAS O DE CUALQUIER OTRA INDOLE QUE PUEDAN CAUSAR CUALQUIER TIPO DE DA&Ntilde;O. ASIMISMO EL ARRENDATARIO SE COMPROMETE A OBTENER TODOS LOS PERMISOS Y AUTORIZACIONES QUE LAS LEYES Y AUTORIDADES EXIJAN CON RESPECTO A CUALQUIER INSTALACION O SUSTANCIA QUE PUDIERE ALBERGAR EL INMUEBLE MATERIA DE ESTE CONTRATO. </p>
      <p>&#149;&nbsp; A CUBRIR CUALQUIER PAGO DE LOS SERVICIOS DE LUZ, AGUA, TELEFONO Y GAS CON PUNTUALIDAD, SIN IMPORTAR QUE LOS RESPECTIVOS CONTRATOS DE SUMINISTROS DE ESTOS SERVICIOS CONTINUEN A NOMBRE DEL ARRENDADOR, AL TERMINAR EL PRESENTE CONTRATO EL ARRENDATARIO SE OBLIGA A ENTREGAR JUNTO CON EL LOCAL MATERIA DEL PRESENTE CONTRATO LOS RECIBOS CON QUE SE ACREDITE ESTAR AL CORRIENTE EN EL PAGO DE DICHOS SERVICIOS. </p>
      <p>&#149;&nbsp; A HACER TODO LO POSIBLE PARA EVITAR QUE SUS EMPLEADOS, CLIENTES O AMIGOS Y DEMAS PERSONAS QUE ACUDAN AL LOCAL ARRENDADO CAUSEN DA&Ntilde;O A ESTE. </p>
      <p>DECIMA.- <strong>{aval}</strong>, CONVIENE Y ESTA DE ACUERDO EN SER FIADOR DE <strong>{arrendatario}</strong> Y SE OBLIGA SOLIDARIA Y MANCOMUNADAMENTE AL CUMPLIMIENTO DE LAS OBLIGACIONES ASUMIDAS POR EL ARRENDATARIO EN EL PRESENTE CONTRATO. EN ESTE ACTO EL FIADOR RENUNCIA EXPRESAMENTE A LOS BENEFICIOS DE ORDEN Y EXCLUSION ESTABLECIDOS EN LOS ARTICULOS 2814 Y 2815 DEL CODIGO CIVIL PARA EL DISTRITO FEDERAL </p>
      <p>ASIMISMO MANIFIESTA EL FIADOR QUE ES PROPIETARIO DEL BIEN INMUEBLE UBICADO EN LA SIGUIENTE DIRECCION: <br>
      <strong>{direccion_aval} </strong></p>
    </td>
  </tr>
</table>
<br style="page-break-after:always">
<table width="95%" >
  <tr>
    <td width="10%">&nbsp;</td>
    <td align="justify"><p>DECIMA PRIMERA.- EL ARRENDATARIO DEBERA DESOCUPAR Y ENTREGA LA LOCALIDAD ARRENDADA INMEDIATAMENTE QUE LLEGUE A SU TERMINO EL PRESENTE CONTRATO Y SI NO LO HICIERE DE ACUERDO CON LA CLAUSULA REQUERIDA Y SIN QUE SE CONSIDERE RENOVADO O PROLONGADO EL MISMO, EL ARRENDADOR Y SU FIADOR CONVIENEN Y ACEPTAN QUE A PARTIR DEL SIGUIENTE DIA DE SU VENCIMIENTO Y DURANTE EL PLAZO QUE DILATE POR LA CAUSA QUE SEA EN DESOCUPAR Y ENTREGAR AL ARRENDADOR LA LOCALIDAD ARRENDADA , SE COMPROMETEN A CUBRIR LA CANTIDAD DE $<strong>{cantidad_numero2}</strong> *<strong>{cantidad_letra2}</strong>* MAS IVA. POR RENTA MENSUAL Y SI PERSISTE EL ARRENDAMIENTO VENCIDO POR EL TERMINO DE MAS DE UN A&Ntilde;O, CUBRIRAN UN 30% MAS DE DICHA CANTIDAD, POR CADA A&Ntilde;O QUE TRANSCURRA. </p>
      <p>DECIMA SEGUNDA.- EL IMPORTE DEL COSUMO DE AGUA DEL INMUEBLE ARRENDADO SERA PAGADO POR EL ARRENDATARIO, DEBIENDO EL ARRENDADOR DETALLAR DICHO IMPORTE EN EL RECIBO DE RENTA. </p>
      <p>EL PRESENTE CONTRATO LAS PARTES SIGNANTES, LO REALIZAN SIN ERROR, DOLO O MALA FE O CUALQUIER VICIO DE CONSENTIMIENTO QUE PUDIERA OCURRIR, RENUNCIANDO EXPRESAMENTE AL TRIBUNAL COMPETENTE DE LA LOCALIDAD ARRENDADA , O DE CUALQUIER OTRO TRIBUNAL QUE PUDIERA CORRESPONDERLES, DE ACUERDO A SU DOMICILIO PRESENTE O FUTURO, Y SE SOMETEN EN FORMA EXCLUSIVA A LAS DISPOSICIONES DE LOS TRIBUNALES LOCALES DEL FUERO COMUN DE LA CIUDAD DE MEXICO, ASI COMO A LO CONTENIDO EN SUS CODIGOS APLICABLES. </p>
	  <p>NOTA: VIGENCIA DEL CONTRATO A PARTIR DEL DIA {fecha_inicial} Y VENCIENDO EL DIA {fecha_final} </p>
      <p>&nbsp; </p>
	  <p>&nbsp; </p>
	  <p>&nbsp; </p>
      <p align="center">________________________<br>ARRENDATARIO <br> {arrendatario} <br> {representante_arrendatario} </p>
      <p>&nbsp; </p>
	  <p>&nbsp; </p>
	  <p>&nbsp; </p>
      <p align="center">________________________<br>ARRENDADOR <br> {arrendador} <br> {representante_arrendador} </p>
      <p>&nbsp; </p>
	  <p>&nbsp; </p>
	  <p>&nbsp; </p>
      <p align="center">________________________<br>FIADOR <br> {aval} </p>

    </td>
  </tr>
</table>
